site_name: AMRT
site_url: https://docs.amrt.ca/
repo_url: https://github.com/ammaar-e/mk-amrt
repo_name: ammaar-e/mk-amrt
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - search.suggest
    - search.share
    - navigation.tabs
    - navigation.path
    - navigation.path
    - navigation.footer
##
plugins:
  - search
  - privacy
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: ammaar-e/mk-amrt
      branch: main
  - git-authors
##
extra_css:
  - stylesheets/extra.css
##
extra:
  analytics:
    provider: google
    property: G-Y9WJ072L8V
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - manage
      - accept
      - reject 
  social:
    - icon: fontawesome/brands/discord
      name: Ammaar's Profile
      link: https://discordapp.com/users/543249594352664615
    - icon: fontawesome/brands/github
      name: Ammaar's GitHub
      link: https://github.com/Ammaar-e

##
copyright: >
  Copyright &copy; 2025 AMRT Development Inc. –
  <a href="#__consent">Change cookie settings</a>